### ISSUE TITLE
investigate packet loss in our volunteer mixnet

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#106]
1. What is part of the mixserver's internal pipeline is dropping the packet?
2. Run Prometheus on one or more mix nodes. Collect many statistics. Collect internal mixserver statistics.
3. Answer questions like: 
 a. What is the average packet rate during the packet loss?
 b. Is the packet loss just one packets at a time or several?
 c. Do we think the packet loss is a normal consequence of bandwidth spikes?
 d. What is our current traffic ratio of decoys to normal messages?

**Comment by mixmasala** [comment]
#171
