### ISSUE TITLE
replace AVL tree with priority queue in decoy traffic module of mix server

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#134]
AVL tree library has a bug... let's just not use an AVL tree. Priority  queue is fine for this task most likely. Otherwise if it must be an AVL tree (i highly doubt it) then we fix the bug in the AVL tree.

**Comment by threebithacker** [comment]
I believe we fixed this in https://github.com/katzenpost/katzenpost/pull/221 - reopen if you disagree @david415
