### ISSUE TITLE
fix mixserver memory queue

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#213]
The priority queue used by our core/queue implementation of a priority queue does not properly handle insertions of duplicate priorities. the old one gets overwritten. This is causing subtle bugs and probably packet loss.

This code snippet shows that we don't do anything to prevent duplicate priorities since they are chosen with entropy:
https://github.com/katzenpost/katzenpost/blob/main/server/internal/scheduler/queue_mem.go#L57-L78

**Comment by mixmasala** [comment]
merged in #216
