### ISSUE TITLE
add client benchmark tests

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#224]
https://github.com/katzenpost/katzenpost/tree/add_client_benchmarks

remaining / extra tasks:
* parse the collected metrics from prometheus and produce some useful output
* augment genconfig to parametize network parameters 
* add benchmark makefile target

nice to haves:
* collect other useful metrics from the client
* add make flag to enable mixserver prometheus metrics 
* collect promethes metrics from mixnet  and produce some useful output

**Comment by leif** [comment]
fixed in #247
