### ISSUE TITLE
testnet: detect and usefully log about warped= true/false mismatch

### ISSUE THREAD

**Issue by leif** [katzenpost/katzenpost#261]
when testing katzen against a containerized testnet, katzen must be built with `warped=true` (assuming the testnet is run that way, as is the default).

using katzen without warped=true on a warped testnet results in a failure; it would be nice if we could log a useful error about this.

unfortunately I'm not sure how this could be easily done, as the only indicator the client has is that there is no PKI doc for the current epoch...

**Comment by mixmasala** [comment]
I think the authority can just return a new error type if the requested epoch is way way off.

**Comment by mixmasala** [comment]
This is probably best solved by making Katzen log the error returned, because a developer testing Katzen with warped=true can see that their testnet has bootstrapped
