### ISSUE TITLE
make sure our PQ Noise protocol is designed properly (is secure)

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#27]
Two things

1.
Currently we use Noise XX with Kyber in a hybrid forward secret construction. If I recall correctly we are using Kyber NIST round 3 variant. We should learn the new Kyber parameters from NIST round 4.

2.
@Yawning and a few others have written a paper about proper PQ Noise protocol construction. We need to check to make sure our Noise XX Kyber HFS construction is correct and matches the advice from their paper: https://eprint.iacr.org/2022/539

**Comment by Yawning** [comment]
The code used for the paper is at: https://gitlab.com/yawning/nyquist/-/tree/experimental/pqnoise

It *should* be up to date, but I should double check it at some point.  I probably won't merge this until I have a Kyber implementation that isn't from CIRCL.  Not that I have major problems with the library, but I am trying to keep Nyquist's dependencies somewhat minimal.

**Comment by david415** [comment]
Currently Katzenpost uses https://github.com/katzenpost/noise/blob/master/patterns.go#L92
XXhfs defined like this:

```
var HandshakeXXhfs = HandshakePattern{
	Name: "XXhfs",
	Messages: [][]MessagePattern{
		{MessagePatternE, MessagePatternE1},
		{MessagePatternE, MessagePatternDHEE, MessagePatternEKEM1, MessagePatternS, MessagePatternDHES},
		{MessagePatternS, MessagePatternDHSE},
	},
}
```

whereas nyquist has different way to express patterns it seems:

https://gitlab.com/yawning/nyquist/-/blob/experimental/pqnoise/pattern/pq_interactive.go#L96

```
	// PqXX is the pqXX interactive (fundemental) pattern.
	PqXX Pattern = &builtIn{
		name: "pqXX",
		messages: []Message{
			{Token_e},
			{Token_ekem, Token_s},
			{Token_skem, Token_s},
			{Token_skem},
		},
		isKEM: true,
	}
```

I'll have to finish reading the paper and then decide if our Noise XXhfs + Kyber needs to be changed.

**Comment by Yawning** [comment]
> whereas nyquist has different way to express patterns it seems

nyquist pattern expression attempts to be as close to the original noise spec (and our paper in the branch) as possible.  The evaluation logic also mimics the spec (the responder/initiator goes through each line of tokens, and either does read or write actions).

From our paper:
```
pqXX:
-> e
<- ekem, s
-> skem, s
<- skem
```

The arrows can be elided under the assumption that the initiator talks first (there are never 2 messages back-to-back in the same direction), and as you can see, there is a one-to-one correspondence to the pattern produced for the paper, and the contents of the `Message` field.

`handshakestate_kem.go` has the handers for each side, and `handshakestate.go` has the control flow (see `HandshakeState.ReadMessage` and `HandshakeState.WriteMessage`).

**Comment by david415** [comment]
Yeah very different from the older noise Katzenpost is now using.

I think katzenpost should eventually use nyquist. Kinda want to use that experimental branch right now. But I don't have time to work on this right now.

**Comment by Yawning** [comment]
For what it's worth, the old hfs extension is fine for what it was intended to do, which is preserve confidentiality of historical traffic against quantum adversaries.

If you want something that holds up against active attackers that happen to have a quantum computer, then you would need something like PQ Noise, but that sort of adversary is largely beyond Katzenpost's threat model (since you also will need PQ Sphincs, and signatures).

**Comment by david415** [comment]
Okay. Thanks for the info. I think we now want to upgrade our threat model. Use your nyquist pqnoise stuff eventually. Upgrade the PKI to use sphincs signatures or whatever latest best hash based signature scheme.

I have your sphinx working with a generalized NIKE interface... and more specifically I have tested this with CTIDH and the current ecdh. Works and of course the CTIDH is hella slow. I need to write benchmark tests for the CTIDH key sizes.

https://github.com/katzenpost/katzenpost/blob/nike_sphinx/core/crypto/nike/nike.go

https://github.com/katzenpost/katzenpost/pull/30

https://ctidh.isogeny.org/

Anyway we are a long way off from having this all working.

Unfortunately I had to use cgo. This fucks up our build system and makes it much more of pain having to set a bunch of env vars and having a C library dependency etc. All the shitty details documented here:

https://git.xx.network/elixxir/ctidh_cgo

So far I'm happy with my CTIDH API. Even got some cgo schooling from the go-nuts mailing list:
https://groups.google.com/g/golang-nuts/c/DW9aGznYhZE

**Comment by david415** [comment]
@Yawning I just realized your pqNoise paper specifically mentioned that you don't present us with any hybrid protocols. Any particular reason for the omission? I mean... aren't hybrid protocols what we should be using rather than only depending on Kyber1024?

**Comment by Yawning** [comment]
From the paper:
> We remark here that our proof does in
fact not just apply to the specific PQNoise patterns that
we specify, but to every PQNoise-protocol, including for
example hybrid ones (which we don’t specify here).

Theory vs practice difference I guess.  The patterns and security proofs are valid when using a hybrid construct.

**Comment by david415** [comment]
Alright well I've got a patch to core/wire that makes it use nyquist Noise_pqXX_Kyber1024_ChaChaPoly_BLAKE2s
https://github.com/katzenpost/katzenpost/pull/33

**Comment by Yawning** [comment]
Please keep in mind that I'm not sure what I'm going to do with that branch long term, and though it is coded to my usual standard, it was primarily for a research paper.

CIRCL has `kem/hybrid` that provides a Kyber512 + X25519 construct that implements the package's `kem.Scheme` interface.  Supporting that would be a 2 line change to nyquist's `kem/kem.go`.  I guess I should have exposed the ctor for the CIRCL KEM scheme wrapper instead of keeping it package private...

**Comment by david415** [comment]
@Yawning Okay for the time being I'll fork nyquist and make it work with a hybrid scheme. Later on if you decide to maintain a nyquist feature like this then I'll do the work to make katzenpost use that.

Yeah the kem.Scheme interface approach seems like a very easy way to get a hybrid noise protocol. I like that it's a very small code change. Thanks for pointing that out.

**Comment by david415** [comment]
done
