### ISSUE TITLE
add ppc64le support to  "github.com/henrydcase/nobs/dh/csidh"

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#270]
"github.com/henrydcase/nobs/dh/csidh" doesn't build on ppc64le - but apparently it used to work. Figure out what happened.

**Comment by mixmasala** [comment]
see workaround for running nodes out of our monorepo: https://github.com/katzenpost/katzenpost/pull/269

**Comment by leif** [comment]
i think nobs csidh actually never was working on ppc64le, but it wasn't a problem for us to run an auth or mix until after #246 landed (which adds an optional hybrid csidh sphinx...).
