### ISSUE TITLE
Noise message padding for all mixnet commands

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#371]
We'd like to pad all Noise protocol messages that the mixnet uses such that they are all the same size as the Message command containing Sphinx packets. The outlier of course is the Consensus command which contains very large PKI documents of around ~200k for the docker mixnet.

These are the wire protocol commands:
https://github.com/katzenpost/katzenpost/tree/main/core/wire/commands

The basic idea is that we want each of these wire commands to serialize to the same size so that a passive network observer cannot determine which command is being sent or received. This task should be done along with unit tests that show that all the wire protocol commands are all the same size. The tests should serialize each command and then check that they are all the same size.

**Comment by amitbasuri** [comment]
Hi @david415 I've reviewed the implementation of command serialization and noticed that we currently handle different command lengths specifically tailored to each command's requirements. 

Now to prevent traffic analysis by standardizing command lengths, I propose two approaches, considering the unique size of the Consensus command:

#### Proposal 1: Uniform Command Size
- **Uniform Size**: Adopt a `maxCommandSize` across all commands, set at the size needed for the largest command (potentially 210 KB).
- **Zero Padding**: Implement zero-padding for all commands up to the `maxCommandSize`.

#### Proposal 2: Special Handling for Consensus
- **Reduced Size for Common Commands**: Set a smaller `maxCommandSize` for regular commands (e.g., 100 KB).
- **Separate Treatment for Consensus**: Allow the Consensus command to exceed this size, using segmentation or a higher limit.

**Discussion Points:**
- Which approach better balances security with operational efficiency?

Looking forward to your thoughts on which strategy might be more effective for our needs.

**Comment by david415** [comment]
@amitbasuri Good summary. I'd like us to implement Proposal 2.

**Comment by david415** [comment]
fixed forever!
