### ISSUE TITLE
mix server data race

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#396]
==================
WARNING: DATA RACE
Write at 0x0000014ae7e8 by goroutine 13:
  github.com/katzenpost/katzenpost/server/internal/instrument.SetKaetzchenRequestsTimer()
      /home/runner/work/katzenpost/katzenpost/server/internal/instrument/prometheus.go:252 +0x19b
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*KaetzchenWorker).processKaetzchen()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen.go:189 +0x8b
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*KaetzchenWorker).worker()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen.go:184 +0x62a
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*KaetzchenWorker).worker-fm()
      <autogenerated>:1 +0x39
  github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
      /home/runner/work/katzenpost/katzenpost/core/worker/worker.go:39 +0x73

Previous write at 0x0000014ae7e8 by goroutine 11:
  github.com/katzenpost/katzenpost/server/internal/instrument.SetKaetzchenRequestsTimer()
      /home/runner/work/katzenpost/katzenpost/server/internal/instrument/prometheus.go:252 +0x19b
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*KaetzchenWorker).processKaetzchen()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen.go:189 +0x8b
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*KaetzchenWorker).worker()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen.go:184 +0x62a
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*KaetzchenWorker).worker-fm()
      <autogenerated>:1 +0x39
  github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
      /home/runner/work/katzenpost/katzenpost/core/worker/worker.go:39 +0x73

Goroutine 13 (running) created at:
  github.com/katzenpost/katzenpost/core/worker.(*Worker).Go()
      /home/runner/work/katzenpost/katzenpost/core/worker/worker.go:37 +0x116
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.New()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen.go:295 +0x7e7
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.TestKaetzchenWorker()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen_test.go:276 +0xbf3
  testing.tRunner()
      /opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1629 +0x47

Goroutine 11 (running) created at:
  github.com/katzenpost/katzenpost/core/worker.(*Worker).Go()
      /home/runner/work/katzenpost/katzenpost/core/worker/worker.go:37 +0x116
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.New()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen.go:295 +0x7e7
  github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.TestKaetzchenWorker()
      /home/runner/work/katzenpost/katzenpost/server/internal/provider/kaetzchen/kaetzchen_test.go:276 +0xbf3
  testing.tRunner()
      /opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1629 +0x47
==================

**Comment by mixmasala** [comment]
https://github.com/katzenpost/katzenpost/issues/398

**Comment by mixmasala** [comment]
https://github.com/katzenpost/katzenpost/issues/363
