### ISSUE TITLE
doubleratchet does not use keysizes from scheme

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#598]
in doubleratchet/constants.go there are hardcoded key sizes
e.g. DoubleRatchetOverhead depends on github.com/henrydcase/nobs/dh/csidh.PublicKeySize. See also headerSize. 

I think we just need to make headerSize be determined when a Ratchet is intantiated by calling Ratchet.scheme.PublicKeySize().

To verify that this bug will produce a crash, switch to using a scheme with larger keysizes:
```
diff --git a/doubleratchet/ratchet_test.go b/doubleratchet/ratchet_test.go
index 1f6dd6af..00c1c714 100644
--- a/doubleratchet/ratchet_test.go
+++ b/doubleratchet/ratchet_test.go
@@ -7,12 +7,13 @@ import (
 
 	"github.com/stretchr/testify/require"
 
-	ecdh "github.com/katzenpost/hpqc/nike/x25519"
+	//ecdh "github.com/katzenpost/hpqc/nike/x25519"
+	"github.com/katzenpost/hpqc/nike/hybrid"
 )
 
-var nikeScheme = ecdh.Scheme(rand.Reader)
+//var nikeScheme = ecdh.Scheme(rand.Reader)
 
-//var nikeScheme = hybrid.CTIDHX25519
+var nikeScheme = hybrid.CTIDH2048X25519
 
 func pairedRatchet(t *testing.T) (aRatchet, bRatchet *Ratchet) {
 	var err error
```

it would be good to also refactor ratchet_test.go to run tests using all of the available schemes.

**Comment by david415** [comment]
we fixed this yesterday
