### ISSUE TITLE
BUG: Dropping packets; Sphinx invalid MAC

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#635]
We currently have a very bad packet dropping bug in Katzenpost main.  The bug is undoubtedly located in the cryptoworker: https://github.com/katzenpost/katzenpost/blob/main/server/internal/cryptoworker/crypto_worker.go

This bug causes packet loss with this debug log message:
```
07:45:59.730 DEBU crypto:0: Dropping packet: 65846 (sphinx: invalid packet, MAC mismatch)
07:47:59.268 DEBU crypto:1: Dropping packet: 67480 (sphinx: invalid packet, MAC mismatch)
07:49:59.926 DEBU crypto:1: Dropping packet: 68989 (sphinx: invalid packet, MAC mismatch)
```

**Comment by amitbasuri** [comment]
@david I added test case for crypto_worker here https://github.com/katzenpost/katzenpost/pull/637 
I am getting this same error however I am not sure if the test case is correct 

```
17:57:45.281 DEBU crypto:0: Packet: 7 (Unwrap took: 1.781881ms)
    crypto_worker_test.go:194: 
                Error Trace:    /workspaces/katzenpost/server/internal/cryptoworker/crypto_worker_test.go:194
                Error:          Received unexpected error:
                                cryptoWorker should unwrap packet without error: sphinx: invalid packet, MAC mismatch
                Test:           TestCryptoWorkerUnwrap
                Messages:       CryptoWorker should unwrap packet without error
17:57:45.281 DEBU crypto:0: Packet: 8 (Unwrap took: 1.844958ms)
    crypto_worker_test.go:194: 
                Error Trace:    /workspaces/katzenpost/server/internal/cryptoworker/crypto_worker_test.go:194
                Error:          Received unexpected error:
                                cryptoWorker should unwrap packet without error: sphinx: invalid packet, MAC mismatch
                Test:           TestCryptoWorkerUnwrap
```

Ful log: https://github.com/katzenpost/katzenpost/actions/runs/9487429524/job/26144056146

**Comment by david415** [comment]
@amitbasuri Good try. The reason your test is failing with the exact same error as the bug report is because that's the error message that is emitted when the mix node does not have the appropriate private key with which to unwrap the Sphinx packet. But don't go fixing your tests, we actually need something different; we need the routing logic to be separated into it's own function or method. Here I've made it a method:

https://github.com/katzenpost/katzenpost/pull/638/files

with a function signature like this:

```
func (w *Worker) routePacket(pkt *packet.Packet, startAt time.Time) {
```

And I started to add a unit test but didn't get very far.
What we need to do is write various tests for testing the routing behavior of each node type:
1. mix node
2. gateway node
3. service node

Whether or not the routing logic behaves like a specific node type is dependent on the configuration we give it... a mix server configured to be a gateway node will have the Gateway portion of the configuration present etc.

The various test cases are determined by fields set within the `packet.Packet` struct type. We need a data drive set of tests where each test case is determined by the fields set on the packet for example packet has various methods which we use to determine what kind of packet it is:

```
// IsForward returns true iff the packet has routing commands indicating it is
// a forward packet destined for another hop.
func (pkt *Packet) IsForward() bool {
	return pkt.NextNodeHop != nil && pkt.NodeDelay != nil && pkt.Recipient == nil && pkt.SurbReply == nil
}

// IsToUser returns true iff the packet has routing commands indicating it is
// a forward packet destined for a local user.
func (pkt *Packet) IsToUser() bool {
	return pkt.NextNodeHop == nil && pkt.NodeDelay != nil && pkt.Recipient != nil && pkt.SurbReply == nil
}

// IsSURBReply returns true iff the packet has routing commands indicating it
// is a SURB Reply destined for a local user.
func (pkt *Packet) IsSURBReply() bool {
	return pkt.NextNodeHop == nil && pkt.NodeDelay == nil && pkt.Recipient != nil && pkt.SurbReply != nil
}
```

**Comment by david415** [comment]
We are in fact also solving for this ticket here https://github.com/katzenpost/katzenpost/issues/611

**Comment by david415** [comment]
@amitbasuri I made some progress and now have the routing logic fully tested in this PR: https://github.com/katzenpost/katzenpost/pull/638

Do you have any test cases to add to it? If so you can branch off of that branch and push commits and open a new pr.

I couldn't find any errors in the routing logic... and due the the data driven testing it's clear that the routing logic is correct for each of the node types. What else could be causing packet loss? This particular packet loss error only happens when a node receives a Sphinx packet for which it has no private key to unwrap it. Therefore I suspected the routing logic might be causing packets to go to the wrong place and thus get dropped. But no, that wasn't the problem.

Pyroscope might be useful here.

Collecting mix node debug logs might be useful.

Testing with a test mixnet might be useful. Can you deploy a minimal test mixnet and test it with 100 or so clients? Xen has automated the deployment of clients. While the mixnet is booting up there will be some packet loss because the incoming worker goroutine receives packets before the outgoing goroutine has connected to the outbound mix node, thus the packets will get dropped while the mix node is booting up. After fully connected/booted there shouldn't be any packet loss. Especially when Eva says the mixnet can handle 600 clients and it can barely handle 100 clients with 60% packet loss...

**Comment by david415** [comment]
@amitbasuri This is likely falsely reported bug due to a mismatch in katzenpost versions between client and mixnet. So I'm going to close this ticket for now.
