### ISSUE TITLE
BUG: service node handshake failures

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#636]
We have wire authentication handshake failures on the Service Nodes; this is a bug.

**Comment by xendarboh** [comment]
Within a test with 95 ping clients, service2 has tons (7587) of these, while service1 had 6, and mix1,2,3 each have some

```
04:11:40.357 ERRO incoming:7304: Handshake failed: unexpected EOF
```

**Comment by david415** [comment]
likely falsely reported bug due to a mismatch in katzenpost versions between client and mixnet...
