### ISSUE TITLE
client2 tests cannot be interrupted with control-c

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#673]
The shutdown code path of client2 is a little bit messed up since it does not allow us to control-C it to shutdown... when specifically it should do this. This bug only is present when decoy traffic is turned on.

**Comment by mixmasala** [comment]
I found a few bugs while looking at #671 related to #673; see fix_673_sigint

**Comment by david415** [comment]
yes, it works! thanks for the bug fixes! @mixmasala
