### ISSUE TITLE
AltAddresses feature was removed, need it for NATs

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#726]
We need AltAddresses or some equivalent feature set that allows us to use a Gateway node behind a NAT router. The idea here is that AltAddresses tells the dirauth (via mix descriptor) a different address than the one we actually listen on.

e.g. we listen on the network interface associated with 192.168.1.123 but we advertise something else.

The mix server's config has:

```golang

	// If present then only advertise to the PKI these Addresses
	// and do NOT send any of the Addresses.
	OnlyAdvertiseAddresses []string
```

and the mix server's internal pki package has this constructor:

```golang

// New reuturns a new pki.
func New(glue glue.Glue) (glue.PKI, error) {
	p := &pki{
		glue:          glue,
		log:           glue.LogBackend().GetLogger("pki"),
		docs:          make(map[uint64]*pkicache.Entry),
		rawDocs:       make(map[uint64][]byte),
		failedFetches: make(map[uint64]error),
	}

	var err error
	if len(glue.Config().Server.OnlyAdvertiseAddresses) > 0 {
		p.descAddrMap = make(map[string][]string)
		// XXX: parse each address and update descAddrMap
		panic("NotImplemented")
	} else {
		if p.descAddrMap, err = makeDescAddrMap(glue.Config().Server.Addresses); err != nil {
			return nil, err
		}
	}

	if len(p.descAddrMap) == 0 {
		return nil, errors.New("Descriptor address map is zero size.")
	}
```

I think we should just add the old feature back as `AltAddresses`, but if you want to change the name that's fine too.
However you might as well make them both use the new URL format for the addresses.

We need two fields, `Addresses` and `AltAddresses`. If you want to say that `Addresses` should only contain publicly routeable addresses that should be advertised in the PKI, then that's fine. In that case, create a new field called `ListenAddresses` or something like that. 

There is of course another way to solve this: just listen on 0.0.0.0 no matter what addresses are specified, and always advertise all the specified addresses. This would "work" but it removes a feature that we currently have which is the ability to specify precisely which network interfaces to listen on. We currently do not have any multi-homed nodes... however as a research and software dev group, the katzenpost team has not had much experience or inclination to start a large mixnet deployment.... so who are we to say that nobody will ever want to deploy a multi-homed node? Multihomed nodes are quite common at many ISPs.

**Comment by mixmasala** [comment]
I think a good solution is to add a new config field "BindAddresses" which overrides the listeners specified in Addresses, and continues to advertise Addresses. The option "OnlyAdvertiseaAddresses" is removed.
See: df672d827cd94ab9735311dbd0238aaf8990959f (client2)

I tested that this works by stopping a testnet mix node, copying Addresses to BindAddresses and adding an additional listener, and then starting the node.
