### ISSUE TITLE
BUG: 2 CI tasks perpetual unresolved

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#757]
these two tasks never get resolved in the CI:
```
 test_e2e_catshadow (1.22.x, ubuntu-latest) Expected — Waiting for status to be reported
Required
test_e2e_pigeonhole (1.22.x, ubuntu-latest) Expected — Waiting for status to be reported
Required 
```

**Comment by ioerror** [comment]
I found that https://github.com/katzenpost/katzenpost/settings/branch_protection_rules/30598679 set those two jobs to be expected but they are apparently not configured to run, so they won't be satisfied. I have removed them are required tasks for the branch protection, and if we want to gate merges, we should run those tests as part of any PR, and then adding them back to the branch protection should ensure they pass before a merge.
