### ISSUE TITLE
restarting authority fails because old certificate from persistence db is expired

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#83]
I would prefer to not use on-disk persistence because I suspect it might result in conflicting descriptors upon restart that might cause an authority to have a wrong view of the network when making consensus.

**Comment by mixmasala** [comment]
the old authority code used the following value for certificate expiration:
-       CertificateExpiration = (epochtime.Period * 3) + (time.Minute * 10)
so that a certificate is valid for all the epochs its keys are valid + some timeslop
I think partly we're too aggressive on the certificate expiration

**Comment by mixmasala** [comment]
+       signed, err := cert.Sign(signer, verifier, payload, epoch+2)

is the new value

**Comment by mixmasala** [comment]
probably that should actually be epoch+3 because the keys in a consensus are stil valid and the descriptor is being signed in the epoch before it is valid

**Comment by david415** [comment]
fix here https://github.com/katzenpost/katzenpost/pull/104
