### ISSUE TITLE
injecting a mix without permission

### ISSUE THREAD

**Issue by ioerror** [katzenpost/katzenpost#89]
Today on the pqmixnet Namenlos I added a new mix node called `mixy` - I added it to my authority, as did two other dirauths. It appears all five dirauths signed it without it being allow-listed in the dirauth config. If this is correct it is a security issue. An open question is if a mix can be injected simply by knowing the PKI, or if the dirauths will accept it only if one dirauth allow-lists it.

**Comment by mixmasala** [comment]
#88

**Comment by david415** [comment]
the fix was recently merged
